### PR TITLE
Add a simple test case

### PR DESCRIPTION
**Pull request by bignaux**
## Pull Request checklist

Note: these are not necessarily requirements

- [ ] I reformatted the code with clang-format
- [x] I checked to make sure my submission worked
- [x] I am the author of submission or have permission from the original author
- [ ] Requires update of the PS2SDK
- [ ] Requires update of the gsKit
- [ ] Others (please specify below)

## Pull Request description

This is a basic command send/expect base on powerfull expect utility, really straightforward and i think it's better than nothing to detect regression on PR. It can be improved but i'd like to know if it's something that interesting here or if you have other plan for such purpose.

### CODE REVIEW

**Comment by uyjulian** [comment]
This is interesting. Should I merge now or are you going to append to this PR ?

**Comment by bignaux** [comment]
i could go further since you seems interesting, i started it to test scripting pfsshell to batch my OPL to install cover. Since i don't like testing script with my real disk, i've to investigate mkpart issue and also add some comment for future people that would be interesting to script pfsshell with a real solution instead of echoing command in text file or other ugly tricks :D Let me know if you have some requirement, i've idea but that's my first tcl script, and i don't have much time this days (i shouldn't be doing that stuff ^^). Btw, i like time to time merge," Release early, release often".

**Comment by uyjulian** [comment]
I can't think of such requirements right now, so I'll merge for now.

**Comment by AKuHAK** [comment]
Just would like to mention that uyjulian name is hardcoded now :)

**Comment by bignaux** [comment]
@AKuHAK You turn is coming :P

**Pull request merged**
